// Exception class that is generated by the FileSystem and component classes

import java.util.*;
import java.lang.*;
import java.io.*;

class FileSystemException extends Exception {
  String str;

  // Constructor: accept a string
  public FileSystemException(String s) {
    str = s;
  };

  // For display of the exception
  public String toString() {
    return(str);
  };
};